### ISSUE TITLE
Practice 2

### ISSUE THREAD

**Issue by geopimik** [AnishShr/autoware_mini_practice#1]
Please correct the following:
1. Remove printouts from the final node! They are suitable for debugging, but it clutters the console output when the node is finished.
2. I would suggest [creating messages](https://github.com/AnishShr/autoware_mini_practice/blob/main/practice_2/nodes/localization/localizer.py#L55-L62) in the callback! Feels safer. You overwrite the values in the callback, but if something goes wrong and they are not overwritten, then old values will be published, and it might be hard to notice that something is wrong.
3. [Azimuth correction](https://github.com/AnishShr/autoware_mini_practice/blob/main/practice_2/nodes/localization/localizer.py#L79) needs to be subtracted!

**Comment by AnishShr** [comment]
1. Removed printouts from the [node](https://github.com/AnishShr/autoware_mini_practice/blob/main/practice_2/nodes/localization/localizer.py#L65)
2. [Created messages](https://github.com/AnishShr/autoware_mini_practice/blob/fa2e6b85e885d692dcb40e4b160907ec71f73d59/practice_2/nodes/localization/localizer.py#L73C5-L122C100) inside the callback function
3. [Azimuth correction ](https://github.com/AnishShr/autoware_mini_practice/blob/fa2e6b85e885d692dcb40e4b160907ec71f73d59/practice_2/nodes/localization/localizer.py#L66) subtraced

**Comment by AnishShr** [comment]
https://github.com/AnishShr/autoware_mini_practice/commit/b1fd3054a5348d5b3fc7bd6b7de886311d59defa
