### ISSUE TITLE
Practice 5 - points_clusterer

### ISSUE THREAD

**Issue by geopimik** [AnishShr/autoware_mini_practice#6]
1. Remove this commented out code from final node
https://github.com/AnishShr/autoware_mini_practice/blob/5e20a0988fd3f96514ba0b4555655acbacd2e5d4/practice_5/nodes/detection/lidar_cluster/points_clusterer.py#L7-L18

2. [Task 3, point 4](https://github.com/AnishShr/autoware_mini_practice/tree/main/practice_5#3-add-clustering) asks you to add assert statement just in case labels and points are not with equal length. Please add.

**Comment by AnishShr** [comment]
1. Removed unused libraries and commented out imports
https://github.com/AnishShr/autoware_mini_practice/blob/929976c17c76fbbb51928cc8685686ae3819fc1e/practice_5/nodes/detection/lidar_cluster/points_clusterer.py#L3-L10
2. Added assert statement
https://github.com/AnishShr/autoware_mini_practice/blob/929976c17c76fbbb51928cc8685686ae3819fc1e/practice_5/nodes/detection/lidar_cluster/points_clusterer.py#L37

**Comment by geopimik** [comment]
OK
