### ISSUE TITLE
Practice 5 - cluster_detector

### ISSUE THREAD

**Issue by geopimik** [AnishShr/autoware_mini_practice#7]
It seems to work.

This issue is just as a follow up to our slack conversation, I would remove these lines - no need to extra create the `PolygonStamped()` and add a header to it. Works without these.
https://github.com/AnishShr/autoware_mini_practice/blob/5e20a0988fd3f96514ba0b4555655acbacd2e5d4/practice_5/nodes/detection/lidar_cluster/cluster_detector.py#L86-L88

**Comment by AnishShr** [comment]
Removed assigning convex hull as PolygonStamped() msg explicitly, and putting the convex hull points directly to object.convex_hull.polygon.points

https://github.com/AnishShr/autoware_mini_practice/blob/839ba7e1b9386987b49349ec3a6ff0752d82c7be/practice_5/nodes/detection/lidar_cluster/cluster_detector.py#L86

**Comment by geopimik** [comment]
OK
